// Content filter to prevent cyberbullying and inappropriate language
// Blocks common names, teacher references, and profanity

const BLOCKED_WORDS = [
    // Common first/last names to protect privacy
    "john",
    "jane",
    "james",
    "robert",
    "michael",
    "william",
    "david",
    "richard",
    "joseph",
    "thomas",
    "charles",
    "daniel",
    "matthew",
    "anthony",
    "mark",
    "donald",
    "steven",
    "paul",
    "andrew",
    "joshua",
    "kenneth",
    "kevin",
    "brian",
    "george",
    "edward",
    "ronald",
    "timothy",
    "jason",
    "jeffrey",
    "ryan",
    "jacob",
    "gary",
    "nicholas",
    "eric",
    "jonathan",
    "stephen",
    "larry",
    "justin",
    "scott",
    "brandon",
    "benjamin",
    "samuel",
    "frank",
    "gregory",
    "alexander",
    "raymond",
    "patrick",
    "jack",
    "dennis",
    "jerry",
    "tyler",
    "aaron",
    "jose",
    "adam",
    "henry",
    "douglas",
    "zachary",
    "peter",
    "kyle",
    "ewart",
    "jerome",
    "nigel",
    "mary",
    "patricia",
    "jennifer",
    "linda",
    "barbara",
    "elizabeth",
    "susan",
    "jessica",
    "sarah",
    "karen",
    "nancy",
    "betty",
    "margaret",
    "sandra",
    "ashley",
    "kimberly",
    "emily",
    "donna",
    "michelle",
    "dorothy",
    "carol",
    "amanda",
    "melissa",
    "deborah",
    "stephanie",
    "rebecca",
    "sharon",
    "laura",
    "cynthia",
    "kathleen",
    "amy",
    "shirley",
    "angela",
    "helen",
    "anna",
    "brenda",
    "pamela",
    "nicole",
    "samantha",
    "christine",
    "debra",
    "rachel",
    "catherine",
    "carolyn",
    "janet",
    "ruth",
    "maria",
    "heather",
    "diane",
    "virginia",
    "julie",
    "joyce",
    "victoria",
    "kelly",
    "christina",
    "lauren",
    "joan",
    "evelyn",
    "judith",
    "megan",
    "andrea",
    "cheryl",
    "hannah",
    "jacqueline",
    "martha",
    "gloria",
    "teresa",
    "ann",
    "sara",
    "madison",
    "frances",
    "kathryn",
    "janice",
    "jean",
    "alice",
    "abigail",
    "sophia",
    "olivia",
    "isabella",
    "ava",
    "emma",
    "charlotte",
    // German names
    "anna",
    "anna",
    "helena",
    "julia",
    "sebastian",
    "maximilian",
    "lukas",
    "friedrich",
    "wilhelm",
    "otto",
    "karl",
    "fritz",
    "klaus",
    "dieter",
    "werner",
    "helmut",
    "gunter",
    "hans",
    "franz",
    "rolf",
    "horst",
    "gerhard",
    "reinhard",
    "erwin",
    "franz",
    "viktor",
    "siegfried",
    "martin",
    "thomas",
    "Andreas",
    "florian",
    "stefan",
    "oliver",
    "daniel",
    "matthias",
    "christian",
    "johannes",
    "heinrich",
    "burkhard",
    "hilde",
    "marlene",
    "gertrude",
    "ingrid",
    "sigrid",
    "renate",
    "christa",
    "petra",
    "monika",
    "anita",
    "barbara",
    "gabriele",
    "stefanie",
    "christine",
    "michelle",
    "daniela",
    "cornelia",
    "angelika",
    "brigitte",
    "christine",
    "katrin",
    "sandra",
    "claudia",
    "silvia",
    "carla",
    "dora",
    "edith",
    "elke",
    "frieda",
    "gisela",
    "hannelore",
    // Common teacher/staff references
    "teacher",
    "sir",
    "madam",
    "mr.",
    "mrs.",
    "ms.",
    "dr.",
    "prof",
    "principal",
    "headmaster",
    "headmistress",
    "administrator",
    "staff",
    "faculty",
    // German teacher/staff references
    "lehrer",
    "lehrerin",
    "herr",
    "frau",
    "fräulein",
    "direktor",
    "direktorin",
    "schulleiter",
    "schulleiterin",
    "rektor",
    "rektorin",
    "professor",
    "professorin",
    "dozent",
    "dozentin",
    "pädagoge",
    "pädagogin",
    // Hate speech variations (English) - STRICT
    "hate",
    "kill",
    "die",
    "suicide",
    "rape",
    "abuse",
    "attack",
    "threat",
    // German hate speech - STRICT
    "hass",
    "töten",
    "mord",
    "selbstmord",
    "vergewaltigung",
    "missbrauch",
    "überfall",
    "bedrohung",
    "rassist",
    "rassismus",
    "antisemit",
    "antisemitismus",
];

const NAME_PATTERN = /\b[A-Z][a-z]+\s+[A-Z][a-z]+\b/g; // Match "FirstName LastName"

/**
 * Check if text contains blocked words or potential names
 * @param {string} text - The text to check
 * @returns {object} - { isClean: boolean, blockedWord?: string, reason?: string }
 */
export function filterContent(text) {
    if (!text || typeof text !== "string") {
        return { isClean: true };
    }

    const lowerText = text.toLowerCase();

    // Check for blocked words
    for (const word of BLOCKED_WORDS) {
        if (new RegExp(`\\b${word}\\b`, "i").test(lowerText)) {
            return {
                isClean: false,
                blockedWord: word,
                reason: `The word "${word}" is not allowed to prevent cyberbullying.`,
            };
        }
    }

    // Check for potential names (FirstName LastName pattern)
    const names = text.match(NAME_PATTERN);
    if (names && names.length > 0) {
        return {
            isClean: false,
            blockedWord: names[0],
            reason: "Full names are not allowed to protect privacy. Use initials instead.",
        };
    }

    return { isClean: true };
}

/**
 * Censor blocked words in text (for display if needed)
 * @param {string} text - The text to censor
 * @returns {string} - Text with blocked words replaced by ***
 */
export function censorContent(text) {
    if (!text || typeof text !== "string") {
        return text;
    }

    let censored = text;

    for (const word of BLOCKED_WORDS) {
        const regex = new RegExp(`\\b${word}\\b`, "gi");
        censored = censored.replace(regex, "***");
    }

    return censored;
}
